In [ ]:
import torch
import tiktoken
import sys
sys.path.append('../scr')
from dataLoader import GPTDataset
from torch.utils.data import Dataset, DataLoader

In [2]:
print(torch.__version__)

2.5.1


In [3]:
torch.cuda.is_available()

True

In [4]:
tokenizer = tiktoken.get_encoding("gpt2")

In [5]:
text = "Hello, do you like tea? <|endoftext|> In the sunlit terraces of someunknownplace."
integers = tokenizer.encode(text, allowed_special={"<|endoftext|>"})
print(integers)

[15496, 11, 466, 345, 588, 8887, 30, 220, 50256, 554, 262, 4252, 18250, 8812, 2114, 286, 617, 34680, 5372, 13]


In [6]:
strings = tokenizer.decode(integers)
print(strings)

Hello, do you like tea? <|endoftext|> In the sunlit terraces of someunknownplace.


In [7]:
with open("../training_data/the-verdict.txt", "r") as f:
    raw_text = f.read()

In [8]:
dataset = GPTDataset(txt = raw_text, tokenizer=tokenizer, max_length=100, stride=10)

In [9]:
data_iter = iter(dataset)
first_batch = next(data_iter)

In [10]:
first_batch

(tensor([   40,   367,  2885,  1464,  1807,  3619,   402,   271, 10899,  2138,
           257,  7026, 15632,   438,  2016,   257,   922,  5891,  1576,   438,
           568,   340,   373,   645,  1049,  5975,   284,   502,   284,  3285,
           326,    11,   287,   262,  6001,   286,   465, 13476,    11,   339,
           550,  5710,   465, 12036,    11,  6405,   257,  5527, 27075,    11,
           290,  4920,  2241,   287,   257,  4489,    64,   319,   262, 34686,
         41976,    13,   357, 10915,   314,  2138,  1807,   340,   561,   423,
           587, 10598,   393, 28537,  2014,   198,   198,     1,   464,  6001,
           286,   465, 13476,     1,   438,  5562,   373,   644,   262,  1466,
          1444,   340,    13,   314,   460,  3285,  9074,    13, 46606,   536]),
 tensor([  367,  2885,  1464,  1807,  3619,   402,   271, 10899,  2138,   257,
          7026, 15632,   438,  2016,   257,   922,  5891,  1576,   438,   568,
           340,   373,   645,  1049,  5975,   284,

In [ ]:
dataloader = DataLoader(dataset, batch_size=32, shuffle=True, drop_last=True) # drop_last = True drops the last batch if it is shorter than the specified batch_size

In [15]:
dataloader_iter = iter(dataloader)

In [19]:
next(dataloader_iter)

[tensor([[   11,   379,   262,  ...,  6423,   314,   373],
         [ 2011, 20136,   373,  ...,  1108,    26,   290],
         [12036,   683,     0,  ...,   290,   314,   550],
         ...,
         [  438,  1659, 10833,  ...,  1464,   651,  1474],
         [  307,  3723,   319,  ...,   511,  6799,   454],
         [  314,   836,   470,  ...,   284,  1560,   345]]),
 tensor([[  379,   262,  3108,  ...,   314,   373,  2077],
         [20136,   373,  3957,  ...,    26,   290,   314],
         [  683,     0,  3226,  ...,   314,   550,   691],
         ...,
         [ 1659, 10833,   340,  ...,   651,  1474,  1576],
         [ 3723,   319,   683,  ...,  6799,   454,    30],
         [  836,   470, 45553,  ...,  1560,   345,   438]])]